find_package(Doxygen REQUIRED OPTIONAL_COMPONENTS dot)


set(DOXYGEN_CALLER_GRAPH YES)
set(DOXYGEN_CALL_GRAPH YES)
set(DOXYGEN_EXTRACT_ALL YES)
set(DOXYGEN_GENERATE_TREEVIEW YES)
set(DOXYGEN_DOT_IMAGE_FORMAT svg)
set(DOXYGEN_DOT_TRANSPARENT YES)

doxygen_add_docs(doxygen-docs ALL ${PROJECT_SOURCE_DIR})
